(class (attrs public ) org/python/core/PyFinalizableInstance
 (super org/python/core/PyInstance)
 (source "PyFinalizableInstance.java")


(method (attrs public ) <init>([object org/python/core/PyClass] )void
  (limit registers 2)
  ; this: v0 ([object org/python/core/PyFinalizableInstance])
  ; parameter[0] : v1 ([object org/python/core/PyClass])
  (line 19)
  (invoke-direct {v0 v1} org/python/core/PyInstance/<init> [object org/python/core/PyClass] )
  (line 20)
  (return-void )
 )

(method (attrs protected ) finalize()void
  (limit registers 8)
  ; this: v7 ([object org/python/core/PyFinalizableInstance])
  (catch org/python/core/PyException from l6ef72 to l6ef7c using l6efdc)
  (catch org/python/core/PyException from l6ef58 to l6ef66 using l6ef68)
  (label l6ef58)
  (line 25)
  (iget-object v2 v7 org/python/core/PyFinalizableInstance.instclass [object org/python/core/PyClass])
  (iget-object v2 v2 org/python/core/PyClass.__del__ [object org/python/core/PyObject])
  (invoke-virtual {v2 v7} org/python/core/PyObject/__call__ [object org/python/core/PyObject] )
  (label l6ef66)
  (line 38)
  (return-void )
  (label l6ef68)
  (line 26)
  (move-exception v0)
  (line 28)
  (iget-object v2 v7 org/python/core/PyFinalizableInstance.instclass [object org/python/core/PyClass])
  (iget-object v1 v2 org/python/core/PyClass.__del__ [object org/python/core/PyObject])
  (label l6ef72)
  (line 30)
  (const-string v2 "__del__")
  (invoke-virtual {v7 v2} org/python/core/PyFinalizableInstance/__findattr__ [object java/lang/String] )
  (label l6ef7c)
  (move-result-object v1)
  (label l6ef7e)
  (line 33)
  (sget-object v2 org/python/core/Py.stderr [object org/python/core/StdoutWrapper])
  (new-instance v3 java/lang/StringBuilder)
  (const-string v4 "Exception ")
  (invoke-direct {v3 v4} java/lang/StringBuilder/<init> [object java/lang/String] )
  (line 34)
  (iget-object v4 v0 org/python/core/PyException.type [object org/python/core/PyObject])
  (iget-object v5 v0 org/python/core/PyException.value [object org/python/core/PyObject])
  (iget-object v6 v0 org/python/core/PyException.traceback [object org/python/core/PyTraceback])
  (invoke-static {v4 v5 v6} org/python/core/Py/formatException [object org/python/core/PyObject] [object org/python/core/PyObject] [object org/python/core/PyObject] )
  (move-result-object v4)
  (invoke-virtual {v3 v4} java/lang/StringBuilder/append [object java/lang/String] )
  (move-result-object v3)
  (line 35)
  (const-string v4 " in ")
  (invoke-virtual {v3 v4} java/lang/StringBuilder/append [object java/lang/String] )
  (move-result-object v3)
  (invoke-virtual {v3 v1} java/lang/StringBuilder/append [object java/lang/Object] )
  (move-result-object v3)
  (line 36)
  (const-string v4 " ignored")
  (invoke-virtual {v3 v4} java/lang/StringBuilder/append [object java/lang/String] )
  (move-result-object v3)
  (invoke-virtual {v3} java/lang/StringBuilder/toString )
  (move-result-object v3)
  (line 33)
  (invoke-virtual {v2 v3} org/python/core/StdoutWrapper/println [object java/lang/String] )
  (goto l6ef66)
  (label l6efdc)
  (line 31)
  (move-exception v2)
  (goto l6ef7e)
)

)
